src/BinaryMash.Web.Mvc4/Models/Question/Preview.cs
namespace BinaryMash.Web.Mvc4.Models.Question
{
    using System;
    using Domain;

    public class Preview
    {
        public bool IsAuthenticated { get; set; }
        public Guid? UserAccountId { get; set; }
        public QuestionVersion QuestionVersion { get; set; }
        public bool CanEdit()
        {
            if (!UserAccountId.HasValue)
            {
                return false;
            }

            return UserAccountId == QuestionVersion.Question.AccountId;
        }
    }
}

src/BinaryMash.Web.Mvc4/Controllers/PersonController.cs
using System.Web.Mvc;

namespace BinaryMash.Web.Mvc4.Controllers
{
    using System.Data.Entity;
    using System.Linq;
    using Components;
    using DataAccess.Repositories.Contract;

    public class PersonController : BaseUserController
    {

        #region ctor

        public PersonController(IPersonRepository personRepository) : base()
        {
            _personRepository = personRepository;
        }

        #endregion

        [AllowAnonymous]
        public ActionResult Index(int? page, int? pageSize)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            if (!page.HasValue)
            {
                page = 1;
            }

            if (!pageSize.HasValue)
            {
                pageSize = 15;
            }
            else
            {
                if (pageSize > 30)
                {
                    pageSize = 30;
                }
            }

            var query = _personRepository.All(User.Identity)
                                         .Include(p => p.User);

            int numberOfPeople = query.Count();

            var people = query.OrderByDescending(p => p.Name)
                                .Skip((page.Value - 1) * pageSize.Value)
                                .Take(pageSize.Value)
                                .ToList();

            ViewBag.Pager = new Pager(page.Value, numberOfPeople, pageSize.Value, "", 7);

            return View("Index", people);
        }

        #region About

        [AllowAnonymous]
        public ActionResult About()
        {
            return View();
        }

        #endregion

        #region Create

        [AllowAnonymous]
        //TODO: user is authorised to create
        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            //TODO: check that user is allowed to create questions

            return View("CreateEdit", 0);
        }

        #endregion

        #region Edit

        public ActionResult Edit(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            return View("CreateEdit", id);
        }

        #endregion

        #region Summary

        public ActionResult Summary(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            return View("Summary", id);
        }

        #endregion

        private readonly IPersonRepository _personRepository;
    }
}

src/BinaryMash.Web.Mvc4/Controllers/QuestionController.cs
namespace BinaryMash.Web.Mvc4.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Linq;
    using System.Web.Mvc;
    using Components;
    using DataAccess.Repositories.Contract;

    public class QuestionController : BaseUserController
    {

        #region ctor

        public QuestionController(IQuestionVersionRepository questionVersionRepository, ILoginRepository loginRepository)
        {
            _questionVersionRepository = questionVersionRepository;
            _loginRepository = loginRepository;
        }

        #endregion

        #region Index

        [AllowAnonymous]
        public ActionResult Index(int? page, int? pageSize)
        {
            if (!page.HasValue)
            {
                page = 1;
            }

            if (!pageSize.HasValue)
            {
                pageSize = 15;
            }
            else
            {
                if (pageSize > 30)
                {
                    pageSize = 30;
                }
            }

            var query = _questionVersionRepository.Latest(User.Identity)
                                      .Include(q => q.Sections)
                                      .Include("Sections.AnswerContents")
                                      .Include(q => q.User);

            int numberOfQuestions = query.Count();

            var questions = query.OrderByDescending(q => q.Created)
                                .Skip((page.Value - 1) * pageSize.Value)
                                .Take(pageSize.Value)
                                .ToList();

            ViewBag.Pager = new Pager(page.Value, numberOfQuestions, pageSize.Value, "", 7);

            return View("Index", questions);
        }

        #endregion

        #region About

        [AllowAnonymous]
        public ActionResult About()
        {
            return View();
        }

        #endregion

        #region Tagged

        [AllowAnonymous]
        public ActionResult Tagged(string id, int? page, int? pageSize)
        {
            ViewBag.Tag = id;

            if (!page.HasValue)
            {
                page = 1;
            }

            if (!pageSize.HasValue)
            {
                pageSize = 15;
            }
            else
            {
                if (pageSize > 30)
                {
                    pageSize = 30;
                }
            }

            var query = _questionVersionRepository.Tagged(User.Identity, id)
                                                  .Include(qv => qv.Sections)
                                                  .Include(q => q.User);


            //Total number of questions on the tag
            int numberOfQuestions = query.Count();

            //Paged questions we care about
            var questions = query.OrderByDescending(q => q.Updated)
                                 .Skip((page.Value - 1) * pageSize.Value)
                                 .Take(pageSize.Value)
                                 .ToList();

            ViewBag.Pager = new Pager(page.Value, numberOfQuestions, pageSize.Value, "", 7);

            return View("TaggedIndex", questions);
        }

        #endregion

        #region Create

        [AllowAnonymous]
        //[MyAuthorize(Roles = "ManageQuestions", Controller="Question", Action="CreateUnauthenticated")]
        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("CreateUnauthenticated");
            }

            //TODO: check that user is allowed to create questions

            return View("Create", 0);
        }

        #endregion

        #region Edit

        public ActionResult Edit(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("CreateUnauthenticated");
            }

            return View("Create", id);
        }

        #endregion

        #region Preview

        [AllowAnonymous]
        public ActionResult Preview(int id)
        {
            //TODO: use title as id?

            var question = _questionVersionRepository.Latest(User.Identity, id)
                                                     .Include(qv => qv.Question.Tags.Select(t => t.Tag))
                                                     .Include(q => q.User)
                                                     .Include(q => q.Sections.Select(s => s.AnswerContents))
                                                     .FirstOrDefault();

            if (question == null)
            {
                //couldn't find QuestionVersion    
                return View("NotFound");
            }

            Guid? accountId = null;
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                var user = _loginRepository.Get(HttpContext.User.Identity).Select(l => l.User).FirstOrDefault();
                if (user != null)
                {
                    accountId = user.AccountId;
                }
            }

            var model = new Models.Question.Preview
            {
                IsAuthenticated = User.Identity.IsAuthenticated,
                QuestionVersion = question,
                UserAccountId = accountId
            };

            return View(model);
        }

        #endregion

        #region Preview

        [AllowAnonymous]
        public ActionResult Published(int id)
        {
            return View("Published", id);
        }

        #endregion

        #region Summary

        [AllowAnonymous]
        public ActionResult Summary(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("NotFound");
            }

            return View("Summary", id);
        }

        #endregion

        [AllowAnonymous]
        public ActionResult CreateUnauthenticated()
        {
            return View();
        }

        private readonly IQuestionVersionRepository _questionVersionRepository;
        private readonly ILoginRepository _loginRepository;

    }
}

src/BinaryMash.Web.Mvc4/Controllers/TagController.cs
namespace BinaryMash.Web.Mvc4.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Components;
    using DataAccess.Repositories.Contract;

    [AllowAnonymous]
    public class TagController : BaseUserController
    {

        public TagController(ITagRepository tagRepository)
        {
            _tagRepository = tagRepository;
        }

        public ActionResult Index(int? page, int? pageSize)
        {
            if (!page.HasValue)
            {
                page = 1;
            }

            if (!pageSize.HasValue)
            {
                pageSize = 48;
            }
            else
            {
                if (pageSize > 48)
                {
                    pageSize = 48;
                }
            }


            var query = _tagRepository.All(User.Identity);

            int numberOfTags = query.Count();

            var tags = query
                .OrderBy(q => q.Name)
                .Skip((page.Value - 1) * pageSize.Value)
                .Take(pageSize.Value)
                .ToList();

            ViewBag.Pager = new Pager(page.Value, numberOfTags, pageSize.Value, "", 7);

            return View("Index", tags);            
        }

        #region About

        public ActionResult About()
        {
            return View();
        }

        #endregion

        public ActionResult Details(string id)
        {
            var tag = _tagRepository.Named(User.Identity, id).FirstOrDefault();

            if (tag == null)
            {
                //couldn't find tag 
                return View("NotFound");
            }

            return View(tag);            
        }

        private readonly ITagRepository _tagRepository;
    }
}

src/BinaryMash.Web.Mvc4/Controllers/TestController.cs
using System.Web.Mvc;

namespace BinaryMash.Web.Mvc4.Controllers
{
    using System.Data.Entity;
    using System.Linq;
    using Components;
    using DataAccess.Repositories.Contract;

    public class TestController : BaseUserController
    {

        public TestController(ITestVersionRepository testVersionRepository)
        {
            _testVersionRepository = testVersionRepository;
        }

        [AllowAnonymous]
        public ActionResult Index(int? page, int? pageSize)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            if (!page.HasValue)
            {
                page = 1;
            }

            if (!pageSize.HasValue)
            {
                pageSize = 15;
            }
            else
            {
                if (pageSize > 30)
                {
                    pageSize = 30;
                }
            }

            var query = _testVersionRepository.Latest(User.Identity)
                                              .Include(tv => tv.User);

            int numberOfTests = query.Count();

            var tests = query.OrderByDescending(t => t.Name)
                                .Skip((page.Value - 1) * pageSize.Value)
                                .Take(pageSize.Value)
                                .ToList();

            ViewBag.Pager = new Pager(page.Value, numberOfTests, pageSize.Value, "", 7);

            return View("Index", tests);

        }

        #region About

        [AllowAnonymous]
        public ActionResult About()
        {
            return View();
        }

        #endregion

        #region Create 

        [AllowAnonymous]
        //TODO: user is authorised to create
        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            //TODO: check that user is allowed to create questions

            return View("CreateEdit", 0);
        }

        #endregion

        #region Edit

        public ActionResult Edit(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            return View("CreateEdit", id);
        }

        #endregion

        #region Summary

        public ActionResult Summary(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            return View("Summary", id);
        }

        #endregion

        #region Published

        [AllowAnonymous]
        public ActionResult Published(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            return View("Published", id);
        }

        #endregion

        private readonly ITestVersionRepository _testVersionRepository;

    }
}

src/BinaryMash.Web.Mvc4/Views/Shared/Components/AnswerContainerCheckbox.cshtml
@model BinaryMash.Domain.AnswerContentQuestionerSupplied

<div class="row">
    <div class="col-xs-12">
        <span class="checkbox">
            <input type="checkbox" disabled="disabled"/> @{ Html.RenderPartial("~/Views/Shared/Components/AnswerContent.cshtml", @Model.Text, new ViewDataDictionary()); }
        </span>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        @{ Html.RenderPartial("~/Views/Shared/Components/Notes.cshtml", @Model.Notes, new ViewDataDictionary()); }
    </div>
</div>    

src/BinaryMash.Web.Mvc4/Views/Shared/Components/AnswerContainerRadio.cshtml
@model BinaryMash.Domain.AnswerContentQuestionerSupplied

<div class="row">
    <div class="col-xs-12">
        <span class="radio">
            <input type="radio" disabled="disabled" /> @{ Html.RenderPartial("~/Views/Shared/Components/AnswerContent.cshtml", @Model.Text); }
        </span>        
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        @{ Html.RenderPartial("~/Views/Shared/Components/Notes.cshtml", @Model.Notes, new ViewDataDictionary()); }
    </div>
</div>

src/BinaryMash.Web.Mvc4/Views/Shared/Components/AnswerContainerSingle.cshtml
@model BinaryMash.Domain.AnswerContentUserSupplied
<div class="row">
    <div class="col-xs-12">
        <p>
            <textarea disabled="disabled" placeholder="The candidate's answer can be up to @Model.MaxLength characters" rows="5" class="atext col-xs-12"></textarea>
        </p>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 anotes">
            @{ Html.RenderPartial("~/Views/Shared/Components/Notes.cshtml", @Model.Notes, new ViewDataDictionary()); }
    </div>
</div>

src/BinaryMash.Web.Mvc4/Views/Shared/Components/AnswerContent.cshtml
@using BinaryMash.Web.Mvc4.Helpers
@model string
<span>@Html.Markdown(@Model)</span>

src/BinaryMash.Web.Mvc4/Views/Shared/Components/Notes.cshtml
@model string

@if (!string.IsNullOrWhiteSpace(@Model))
{    
    <div class="alert alert-info"><span class="glyphicon glyphicon-info-sign"></span> <span>@Model</span></div>
}

src/BinaryMash.Web.Mvc4/Views/Shared/Components/PersonSummary.cshtml
@model BinaryMash.Domain.Person

<div class="row personSummary">
    <div class="col-sm-9 col-md-10">
        <h5>@Html.ActionLink(@Model.Name, "Summary", "Person", new {id = @Model.Id}, null)</h5>       
    </div>
    <div class="col-sm-3 col-md-2">
        <div><small class="text-muted">Updated <span class="updated">@Model.Updated</span> by <span class="updatedBy">@Model.User.DisplayName</span></small></div>
    </div>
</div>
<hr/>

src/BinaryMash.Web.Mvc4/Views/Shared/Components/Question.cshtml
@model BinaryMash.Domain.QuestionVersion
<div class="qaudit">
    <h6><span class="glyphicon glyphicon-list"></span> <span>History</span></h6>
    <small>Version <span class="f-version">@Model.Version</span> (<span class="f-state">@Model.State</span>), created on @Model.Created.ToShortDateString() at @Model.Created.ToShortTimeString() by @Model.User.DisplayName</small>
</div>

src/BinaryMash.Web.Mvc4/Views/Shared/Components/QuestionAndAnswerSection.cshtml
@using BinaryMash.Domain
@using BinaryMash.Web.Mvc4.Helpers
@model BinaryMash.Domain.QuestionAndAnswerSection

<div class="qandasection">
    <div class="row">
        <div class="col-lg-12 qtext">
            @Html.Markdown(@Model.Text)
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 qnotes">
            @{ Html.RenderPartial("~/Views/Shared/Components/Notes.cshtml", @Model.Notes, new ViewDataDictionary()); }
        </div>
    </div>
    <div class="qanswer">
        @foreach (var answer in @Model.AnswerContents.OrderBy(a => a.Index))
        {
            <hr/>      
            switch (@Model.Type)
            {
                case AnswerContainerType.UserSupplied:
                    Html.RenderPartial("~/Views/Shared/Components/AnswerContainerSingle.cshtml", (AnswerContentUserSupplied)answer);
                    break;
                case AnswerContainerType.Radio:
                    Html.RenderPartial("~/Views/Shared/Components/AnswerContainerRadio.cshtml", answer);
                    break;
                case AnswerContainerType.Checkbox:
                    Html.RenderPartial("~/Views/Shared/Components/AnswerContainerCheckbox.cshtml", answer);
                    break;
            }
        }        
    </div>
</div>

src/BinaryMash.Web.Mvc4/Views/Shared/Components/QuestionSummary.cshtml
@using BinaryMash.Web.Mvc4.Helpers
@model BinaryMash.Domain.QuestionVersion

<div class="row questionSummary">
    <div class="col-sm-9 col-md-10">
        <h5>@Html.ActionLink(@Model.Title, "Preview", "Question", new {id = @Model.QuestionId}, null)</h5>
        @Html.MarkdownSummary(Model.Sections.OrderBy(s => s.Index).First().Text, 200)
    </div>
    <div class="col-sm-3 col-md-2">
        <div><small class="text-muted">Created @Model.Created by @Model.User.DisplayName</small></div>
    </div>
</div>
<hr/>

src/BinaryMash.Web.Mvc4/Views/Shared/Components/QuestionTags.cshtml
@model ICollection<BinaryMash.Domain.QuestionTag>
<div class="qtags">
    <h6><span class="glyphicon glyphicon-tags"></span> <span>Tags</span></h6>
    @foreach (var questionTag in @Model)
    {
        <a href="~/Question/Tagged/@Url.Encode(questionTag.Tag.Name)" class="label label-info">@questionTag.Tag.Name</a>
    }
</div>

src/BinaryMash.Web.Mvc4/Views/Shared/Components/QuestionVersion.cshtml
@model BinaryMash.Domain.QuestionVersion

<div class="row">
    <div class="col-xs-12">
        <h2 class="qtitle">@Model.Title</h2>  
        <hr/>      
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-10 qandasections">
        @foreach (var section in @Model.Sections.OrderBy(s => s.Index))
        {
            Html.RenderPartial("~/Views/Shared/Components/QuestionAndAnswerSection.cshtml", section);
        }
    </div>
    <div class="col-xs-12 col-sm-2">
        <hr class="visible-xs"/>        
        @{ Html.RenderPartial("~/Views/Shared/Components/QuestionTags.cshtml", @Model.Question.Tags, new ViewDataDictionary());}
        <hr />
        @{ Html.RenderPartial("~/Views/Shared/Components/Question.cshtml", @Model); }
    </div>
</div>

src/BinaryMash.Web.Mvc4/Views/Shared/Components/SessionSummary.cshtml
@model BinaryMash.Domain.Session

<div class="row sessionSummary">
    <div class="col-sm-9 col-md-10">
        <h5>@Html.ActionLink(@Model.Person.Name+" - "+ @Model.TestVersion.Name, "Summary", "Session", new {id = @Model.Id}, null)</h5>       
        <p class="state">@Model.State</p>
    </div>
    <div class="col-sm-3 col-md-2">
        <div><small class="text-muted">Updated <span class="updated">@Model.Updated</span> by <span class="updatedBy">@Model.User.DisplayName</span></small></div>
    </div>
</div>
<hr/>

src/BinaryMash.Web.Mvc4/Views/Shared/Components/TagSummary.cshtml
@model BinaryMash.Domain.Tag

<div>
    <a class="label label-info" href="~/Question/Tagged/@Url.Encode(Model.Name)">@Model.Name</a>
@*    @Html.ActionLink(@Model.Name, "Details", "Tag", new {id = @Model.Name}, null)  *@
</div>
<div>
    <small>Summary of tag here</small>
</div>

src/BinaryMash.Web.Mvc4/Views/Shared/Components/TestVersionSummary.cshtml
@model BinaryMash.Domain.TestVersion


<div class="row testVersionSummary">
    <div class="col-sm-9 col-md-10">
        <h5>@Html.ActionLink(@Model.Name, "Summary", "Test", new {id = @Model.TestId}, null)</h5>       
    </div>
    <div class="col-sm-3 col-md-2">
        <div><small class="text-muted">Updated <span class="updated">@Model.Updated</span> by <span class="updatedBy">@Model.User.DisplayName</span></small></div>
    </div>
</div>
<hr/>