src/BinaryMash.Web.Mvc4/Models/Session/CreateEdit.cs
namespace BinaryMash.Web.Mvc4.Models.Session
{
    using System;

    public class CreateEdit
    {
        public Guid Id { get; set; }
        public int TestId { get; set; }
        public int TestVersion { get; set; }
        public int PersonId { get; set; }
    }
}

src/BinaryMash.Web.Mvc4/Controllers/PersonController.cs
using System.Web.Mvc;

namespace BinaryMash.Web.Mvc4.Controllers
{
    using System.Data.Entity;
    using System.Linq;
    using Components;
    using DataAccess.Repositories.Contract;

    public class PersonController : BaseUserController
    {

        #region ctor

        public PersonController(IPersonRepository personRepository) : base()
        {
            _personRepository = personRepository;
        }

        #endregion

        [AllowAnonymous]
        public ActionResult Index(int? page, int? pageSize)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            if (!page.HasValue)
            {
                page = 1;
            }

            if (!pageSize.HasValue)
            {
                pageSize = 15;
            }
            else
            {
                if (pageSize > 30)
                {
                    pageSize = 30;
                }
            }

            var query = _personRepository.All(User.Identity)
                                         .Include(p => p.User);

            int numberOfPeople = query.Count();

            var people = query.OrderByDescending(p => p.Name)
                                .Skip((page.Value - 1) * pageSize.Value)
                                .Take(pageSize.Value)
                                .ToList();

            ViewBag.Pager = new Pager(page.Value, numberOfPeople, pageSize.Value, "", 7);

            return View("Index", people);
        }

        #region About

        [AllowAnonymous]
        public ActionResult About()
        {
            return View();
        }

        #endregion

        #region Create

        [AllowAnonymous]
        //TODO: user is authorised to create
        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            //TODO: check that user is allowed to create questions

            return View("CreateEdit", 0);
        }

        #endregion

        #region Edit

        public ActionResult Edit(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            return View("CreateEdit", id);
        }

        #endregion

        #region Summary

        public ActionResult Summary(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            return View("Summary", id);
        }

        #endregion

        private readonly IPersonRepository _personRepository;
    }
}

src/BinaryMash.Web.Mvc4/Controllers/SessionController.cs
using System.Web.Mvc;

namespace BinaryMash.Web.Mvc4.Controllers
{
    using System;
    using System.Globalization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Data.Entity;
    using System.Linq;
    using Components;
    using DataAccess.Repositories.Contract;
    using Agents.Interfaces;
    using Domain;

    public class SessionController : BaseUserController
    {

        #region ctor

        public SessionController(ISessionRepository sessionRepository, ISessionAgent sessionAgent)
        {
            _sessionRepository = sessionRepository;
            _sessionAgent = sessionAgent;
        }

        #endregion

        [AllowAnonymous]
        public ActionResult Index(int? page, int? pageSize)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            if (!page.HasValue)
            {
                page = 1;
            }

            if (!pageSize.HasValue)
            {
                pageSize = 15;
            }
            else
            {
                if (pageSize > 30)
                {
                    pageSize = 30;
                }
            }


            var query = _sessionRepository.All(User.Identity)
                                          .Include("Person")
                                          .Include("User")
                                          .Include("TestVersion");

            int numberOfSessions = query.Count();

            var sessions = query.OrderByDescending(s => s.Id)
                                .Skip((page.Value - 1) * pageSize.Value)
                                .Take(pageSize.Value)
                                .ToList();

            ViewBag.Pager = new Pager(page.Value, numberOfSessions, pageSize.Value, "", 7);

            return View("Index", sessions);
        }

        #region About

        [AllowAnonymous]
        public ActionResult About()
        {
            return View();
        }

        #endregion

        #region Create

        [AllowAnonymous]
        //TODO: user is authorised to create
        public ActionResult Create(int? person, int? test, int? testVersion)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            var model = new Models.Session.CreateEdit
            {
                Id = Guid.Empty,
                TestId = test ?? 0,
                TestVersion = testVersion ?? 0,
                PersonId = person ?? 0
            };

            return View("CreateEdit", model);
        }

        #endregion

        #region Edit

        public ActionResult Edit(Guid id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            var model = new Models.Session.CreateEdit
            {
                Id = id,
            };

            return View("CreateEdit", model);
        }

        #endregion

        #region Summary

        public ActionResult Summary(Guid id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            return View("Summary", id);
        }

        #endregion

        #region TakeNow

        /// <summary>
        /// Take the test directly from when logged in as a user on the site
        /// </summary>
        /// <param name="id">The id.</param>
        /// <param name="password">The password.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TakeNow(Guid id, string password)
        {
            if (_sessionAgent.AuthenticateSession(id, password))
            {
                if (User.Identity.IsAuthenticated)
                {
                    FormsAuthentication.SignOut();
                }

                FormsAuthentication.SetAuthCookie(IdentityConverter.CreateIdentityForSession(id), false);
                return RedirectToAction("Welcome", "Candidate");
            }

            return View("Unauthenticated");
        }

        #endregion
        
        #region Answers

        /// <summary>
        /// View the candidates answers
        /// </summary>
        /// <param name="id">The sessuib id.</param>
        /// <returns></returns>
        public ActionResult Answers(Guid id)
        {
            return View("Answers", null, id.ToString());
        }

        #endregion

        private readonly ISessionRepository _sessionRepository;
        private readonly ISessionAgent _sessionAgent;

    }
}

src/BinaryMash.Web.Mvc4/Controllers/TagController.cs
namespace BinaryMash.Web.Mvc4.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Components;
    using DataAccess.Repositories.Contract;

    [AllowAnonymous]
    public class TagController : BaseUserController
    {

        public TagController(ITagRepository tagRepository)
        {
            _tagRepository = tagRepository;
        }

        public ActionResult Index(int? page, int? pageSize)
        {
            if (!page.HasValue)
            {
                page = 1;
            }

            if (!pageSize.HasValue)
            {
                pageSize = 48;
            }
            else
            {
                if (pageSize > 48)
                {
                    pageSize = 48;
                }
            }


            var query = _tagRepository.All(User.Identity);

            int numberOfTags = query.Count();

            var tags = query
                .OrderBy(q => q.Name)
                .Skip((page.Value - 1) * pageSize.Value)
                .Take(pageSize.Value)
                .ToList();

            ViewBag.Pager = new Pager(page.Value, numberOfTags, pageSize.Value, "", 7);

            return View("Index", tags);            
        }

        #region About

        public ActionResult About()
        {
            return View();
        }

        #endregion

        public ActionResult Details(string id)
        {
            var tag = _tagRepository.Named(User.Identity, id).FirstOrDefault();

            if (tag == null)
            {
                //couldn't find tag 
                return View("NotFound");
            }

            return View(tag);            
        }

        private readonly ITagRepository _tagRepository;
    }
}

src/BinaryMash.Web.Mvc4/Controllers/TestController.cs
using System.Web.Mvc;

namespace BinaryMash.Web.Mvc4.Controllers
{
    using System.Data.Entity;
    using System.Linq;
    using Components;
    using DataAccess.Repositories.Contract;

    public class TestController : BaseUserController
    {

        public TestController(ITestVersionRepository testVersionRepository)
        {
            _testVersionRepository = testVersionRepository;
        }

        [AllowAnonymous]
        public ActionResult Index(int? page, int? pageSize)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            if (!page.HasValue)
            {
                page = 1;
            }

            if (!pageSize.HasValue)
            {
                pageSize = 15;
            }
            else
            {
                if (pageSize > 30)
                {
                    pageSize = 30;
                }
            }

            var query = _testVersionRepository.Latest(User.Identity)
                                              .Include(tv => tv.User);

            int numberOfTests = query.Count();

            var tests = query.OrderByDescending(t => t.Name)
                                .Skip((page.Value - 1) * pageSize.Value)
                                .Take(pageSize.Value)
                                .ToList();

            ViewBag.Pager = new Pager(page.Value, numberOfTests, pageSize.Value, "", 7);

            return View("Index", tests);

        }

        #region About

        [AllowAnonymous]
        public ActionResult About()
        {
            return View();
        }

        #endregion

        #region Create 

        [AllowAnonymous]
        //TODO: user is authorised to create
        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            //TODO: check that user is allowed to create questions

            return View("CreateEdit", 0);
        }

        #endregion

        #region Edit

        public ActionResult Edit(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            return View("CreateEdit", id);
        }

        #endregion

        #region Summary

        public ActionResult Summary(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            return View("Summary", id);
        }

        #endregion

        #region Published

        [AllowAnonymous]
        public ActionResult Published(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View("Unauthenticated");
            }

            return View("Published", id);
        }

        #endregion

        private readonly ITestVersionRepository _testVersionRepository;

    }
}

src/BinaryMash.Web.Mvc4/Controllers/UserController.cs
using System.Web.Mvc;

namespace BinaryMash.Web.Mvc4.Controllers
{
    using System;
    using System.Web;
    using System.Web.Security;
    using Domain;

    public class UserController : BaseUserController
    {
        public ActionResult Home()
        {
            HttpCookie authCookie = Request.Cookies[FormsAuthentication.FormsCookieName];
            FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(authCookie.Value);

            string cookiePath = ticket.CookiePath;
            DateTime expiration = ticket.Expiration;
            bool expired = ticket.Expired;
            bool isPersistent = ticket.IsPersistent;
            DateTime issueDate = ticket.IssueDate;
            string name = ticket.Name;
            string userData = ticket.UserData;
            int version = ticket.Version;

            return View();
        }

        public ActionResult Summary()
        {
            return View("Summary", null, IdentityConverter.ExtractUserId(User.Identity.Name));
        }

        public ActionResult Edit(Guid id)
        {
            return View("Edit", null, id);
        }

        public ActionResult ChangeEmail(Guid id)
        {
            return View("ChangeEmail", null, id);
        }

        public ActionResult ChangePassword()
        {
            return View("ChangePassword", null, IdentityConverter.ExtractId(User.Identity.Name));
        }
    
    }
}

src/BinaryMash.Web.Mvc4/Views/Shared/Headers/Answers.cshtml
<header>
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header navbar-right pull-right">
                <button type="button" class="btn btn-primary btn-sm navbar-btn" data-bind="click: previousQ, css:{disabled:!allowPrevious()}"><span class="glyphicon glyphicon-chevron-left"></span> Previous</button>
                <button type="button" class="btn btn-primary btn-sm navbar-btn" data-bind="click: nextQ, css: { disabled: !allowNext() }">Next <span class="glyphicon glyphicon-chevron-right"></span></button>
                <button type="button" class="btn btn-success btn-sm navbar-btn" data-bind="click: done"><span class="glyphicon glyphicon-ok"></span> Done</button>
            </div>
        </div>
    </nav>
</header>    

src/BinaryMash.Web.Mvc4/Views/Shared/Headers/Blank.cshtml
<header>
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">   
                @Html.ActionLink("[Application image]", "Index", "Home", null, new{@class="navbar-brand"})
            </div>
        </div>
    </nav>
</header>
    

src/BinaryMash.Web.Mvc4/Views/Shared/Headers/CancelDone.cshtml
<header>
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header navbar-right pull-left">
                <button type="button" class="btn btn-warning btn-sm navbar-btn cancelBtn" data-bind="click: cancel, css:{disabled:disableBtns}"><span class="glyphicon glyphicon-remove"></span> Cancel</button>                        
            </div>
            <div class="navbar-header navbar-right pull-right">
                <button type="button" class="btn btn-success btn-sm navbar-btn doneBtn" data-bind="click: done, css: { disabled: disableBtns }"><span class="glyphicon glyphicon-ok"></span> Done</button>
            </div>
        </div>
    </nav>
</header>    

src/BinaryMash.Web.Mvc4/Views/Shared/Headers/Candidate.cshtml
<header>
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">   
                @Html.ActionLink("[Application image]", "Welcome", "Candidate", null, new{@class="navbar-brand"})
            </div>
        </div>
    </nav>
</header>
    

src/BinaryMash.Web.Mvc4/Views/Shared/Headers/CreateEdit.cshtml
<header>
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header navbar-right pull-left">
                <button type="button" class="btn btn-warning btn-sm navbar-btn cancelBtn" data-bind="click: cancel, css:{disabled:disableBtns}"><span class="glyphicon glyphicon-remove"></span> Cancel</button>                        
            </div>
            <div class="navbar-header navbar-right pull-right">
                <button type="button" class="btn btn-primary btn-sm navbar-btn saveBtn" data-bind="click: save, css: { disabled: disableBtns }"><span class="glyphicon glyphicon-floppy-disk"></span> Save</button>        
                <button type="button" class="btn btn-success btn-sm navbar-btn doneBtn" data-bind="click: done, css: { disabled: disableBtns }"><span class="glyphicon glyphicon-ok"></span> Done</button>
            </div>
        </div>
    </nav>
</header>    

src/BinaryMash.Web.Mvc4/Views/Shared/Headers/Test.cshtml
<header>
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header navbar-right pull-right">
                <button type="button" class="btn btn-primary btn-sm navbar-btn" data-bind="click: previousQ, css:{disabled:!allowPrevious()}"><span class="glyphicon glyphicon-chevron-left"></span> Previous</button>
                <button type="button" class="btn btn-primary btn-sm navbar-btn" data-bind="click: nextQ, css: { disabled: !allowNext() }">Next <span class="glyphicon glyphicon-chevron-right"></span></button>
                <button type="button" class="btn btn-success btn-sm navbar-btn" data-bind="click: review, css: {disabled: showSummaryView}"><span class="glyphicon glyphicon-ok"></span> Review and submit</button>
            </div>
        </div>
    </nav>
</header>    

src/BinaryMash.Web.Mvc4/Views/Shared/Headers/User.cshtml
<header>
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">   
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("[Application image]", "Index", "Home", null, new{@class="navbar-brand"})
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Questions","Index","Question", null, new {@id = "questions"})</li>
                    <li>@Html.ActionLink("Tags","Index","Tag", null, new {@id="tags"})</li>
                    <li>@Html.ActionLink("Tests","Index","Test", null, new {@id="tests"})</li>
                    <li>@Html.ActionLink("People","Index","Person", null, new {@id="people"})</li>
                    <li>@Html.ActionLink("Sessions","Index","Session", null, new {@id="sessions"})</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a id="userSummary" href="~/User/Summary"><span class="glyphicon glyphicon-user"></span> My account</a></li>
                        <li><a id="logOut" href="~/Authentication/LogOut"><span class="glyphicon glyphicon-log-out"></span> Log out</a></li>
                    }
                    else
                    {
                        <li><a id="signUp" href="~/Account/Create"><span class="glyphicon glyphicon-pencil"></span> Sign up</a></li>
                        <li><a id="logIn" href="~/Authentication"><span class="glyphicon glyphicon-log-in"></span> Log in</a></li>                            
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
    